# Please *DO NOT* modify this file. Keep it as-is in your repository for the
# duration of the project. Modification/deletion of this file may result in
# your project failing to build or deploy, and in such a scenario, will lead to
# a loss of marks.

name: Scheduled Daily

on: 
  schedule:
    - cron: "30 16 * * *"

jobs:
  scheduled-daily:
    name: Scheduled Daily
    uses: comp30019/ci-cd/.github/workflows/webgl-proj2-sch-daily.yml@main
    secrets: inherit
